#! /bin/sh

case "$1" in
  rebuild)
	echo "Rebuilding po files" >&2
  	../../../../bin/i18ndude rebuild-pot --pot locales/collective.sponsor.pot --create collective.sponsor .
	;;
  sync)
	echo "Syncing po files" >&2
	../../../../bin/i18ndude sync --pot locales/collective.sponsor.pot locales/*/LC_MESSAGES/collective.sponsor.po
	;;
  all)
	echo "Rebuilding po files" >&2
  	../../../../bin/i18ndude rebuild-pot --pot locales/collective.sponsor.pot --create collective.sponsor .
	echo "Syncing po files" >&2
	../../../../bin/i18ndude sync --pot locales/collective.sponsor.pot locales/*/LC_MESSAGES/collective.sponsor.po
	;;
  *)
	echo "Usage: $0 rebuild|sync|all" >&2
	exit 3
	;;
esac